/*
* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
* By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
* By considering the terms in the Fibonacci sequence whose values do not exceed four million,
* find the sum of the even-valued terms.
* */
require('../../scripts/Array');

var max = 4000000;
var current = 1;
var previous = 0;
var next = 0;
var total = [];

var i = 0;

do {
    next = current + previous;
    previous = current;
    current = next;

    if(next % 2 === 0) {
        total.push(next);
    }

} while(next < max);


console.log('');
console.log('');
console.log("Answer " + total.sum());
console.log('');
console.log('');
